.\"                                      Hey, EMACS: -*- nroff -*-
.TH LEXHOLDER\-RU 1 "January 18, 2006"
.SH NAME
lexholder\-ru \- lexical database holding utility
.SH SYNOPSIS
.B lexholder\-ru
.RI [\-q|\-v] [\-i] [\-a] [\-r] [\-f <file>] <db_path>
.br
.B lexholder\-ru
.RI \-l [\-q] [\-f <file>] <db_path>
.br
.B lexholder\-ru
.RI \-s <key> [\-i] [\-q] [\-f <file>] <db_path>
.br
.B lexholder\-ru
.RI \-d <key> [\-i] <db_path>
.br
.B lexholder\-ru
.RI \-h
.SH DESCRIPTION
\fBlexholder\-ru\fP is a small utility intended for use from the
command line or shell-scripts. It allows to create lexical database,
update it and extract it's content in textual form.
.PP
When filling and updating the database,
new records are read from the standard input.
When extracting data from the database,
The result is printed to the standard output.
This behaviour can be changed by the "\fB\-f\fP" switch.
.SH OPTIONS
This utility recognizes following command line options:
.TP
.B \-a
.br
Store all records (redundant too). In this case we use term
"redundant" for the records where key and value are quite identical.
Such record does not contain a pronunciation information, it only affects
the fact of presence of certain word in the lexical database.
.TP
.B \-r
.br
Replace mode. In this mode new records replace existing ones
with the same key. By default such records are ignored.
.TP
.B \-d <key>
.br
Delete record for specified key.
.TP
.B \-s <key>
.br
Search specified key in the lexical database. If the word is found
program exits successfully and outputs it's pronunciation, otherwise
prints the original word (it will be lowercased if the \fB\-i\fP
switch is used) and exits with non-zero return code.
If the \fB\-q\fP switch is specified in the command line, nothing
will be printed on the standard output, but return code still
can be used to find out wether the word was found or not.
.TP
.B \-i
.br
Ignore case in accepted info. All info (both keys and values)
for the lexical database must not contain the uppercase letters.
This option allows using of uppercase letters, all these will be
automatically lowercased before using.
.TP
.B \-l
.br
List database content in textual form.
.TP
.B \-f <file>
.br
Use specified file instead of standard input or output.
.TP
.B \-q
.br
Be more quiet than usual: don't print search results as well
as warnings about redundant and duplicate records.
.TP
.B \-v
.br
Be more verbose than usual: print messages about work stages
and final statistical information when finishing.
.TP
.B \-h
.br
Show summary of options and exit.
.SH SEE ALSO
.BR ru_tts (1), /usr/share/doc/rulex/README.
.SH AUTHOR
Igor B. Poretsky <master@goga.energo.ru>.
